name: Terraform Deploy to LocalStack

on:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.3.9"

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform changes
      run: terraform plan -out=tfplan -var="endpoint=http://192.168.1.137:4566"

    - name: Apply Terraform changes
      run: terraform apply -auto-approve tfplan

